GUFCWebsite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from website import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^website/', include('website.urls')),
    url(r'^admin/', admin.site.urls),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url
from website import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^club',views.club, name='club'),
    url(r'^news', views.club_news, name='club_news'),
    url(r'^teamProfiles', views.teamProfiles, name='teamProfiles'),
    url(r'^firstTeam', views.firstTeam, name='firstTeam'),
    url(r'^secondTeam', views.secondTeam, name='secondTeam'),
    url(r'^thirdTeam', views.thirdTeam, name='thirdTeam'),
    url(r'^underTwentyOnes', views.underTwentyOnes, name='underTwentyOnes'),
    url(r'^matchReports', views.matchReports, name='matchReports'),
    url(r'^add_news/$', views.add_report, name='add_report'),
    url(r'^events/$', views.events, name='events'),
    url(r'^club_captain/$', views.club_captain, name='club_captain'),
]

website/models.py
from django.db import models
from django.template.defaultfilters import slugify
import datetime

# Create your models here.

class News(models.Model):
    name = models.CharField(max_length = 128, unique = True)
    views = models.IntegerField(default = 0)
    slug = models.SlugField(unique = True)

    class Meta:
        verbose_name_plural = "News"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(News, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class Report(models.Model):
    news_cat = models.ForeignKey(News,on_delete=models.PROTECT)
    title = models.CharField(max_length = 128)
    text = models.TextField()
    views = models.IntegerField(default = 0)
    date = models.DateField(default=datetime.date.today)
    image = models.ImageField(upload_to = "report_images/", null = True)

    def __str__(self):
        return self.title

class Events(models.Model):
    

    def __str__(self):
        return self.title

website/forms.py
from django import forms
from website.models import Report, News, Events

class ReportForm(forms.ModelForm):

    news_cat = forms.ModelChoiceField(queryset = News.objects.all())
    title = forms.CharField(max_length = 128, widget =forms.TextInput(attrs = {"placeholder": "Report Title"}))
    text = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Enter text"} ))
    views = forms.IntegerField(widget = forms.HiddenInput(), initial = 0)
    date = forms.DateField(widget=forms.DateInput(format='%m/%d/%Y'))


    class Meta:
        model = Report
        fields = ("news_cat", "title","text","views","date")

website/views.py
from django.http import HttpResponse
from django.shortcuts import render
from website.models import News, Report,Events
from website.forms import ReportForm

def index(request):

    reports = Report.objects.order_by("-views")[:5]
    context_dict = {"news_reports": reports}

    return render(request, 'website/index.html', context_dict)

def club(request):
    
    context_dict = {}
    
    return render(request, 'website/club.html', context = context_dict)

def show_news(request, news_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        news_cat = News.objects.get(slug=news_name_slug)
        # Retrieve all of the associated pages.
        # Note that filter() will return a list of page objects or an empty list
        reports = Report.objects.filter(news_cat=news_cat)
        # Adds our results list to the template context under name pages.
        context_dict['reports'] = reports
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['news_cat'] = news_cat
    except News.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['news_cat'] = None
        context_dict['reports'] = None
    # Go render the response and return it to the client.
    return render(request, 'website/news.html', context_dict)

def teamProfiles(request):
    context_dict = {}

    return render(request, 'website/teamProfiles.html', context=context_dict)

def firstTeam(request):
    context_dict = {}

    return render(request, 'website/firstTeam.html', context=context_dict)

def secondTeam(request):
    context_dict = {}

    return render(request, 'website/secondTeam.html', context=context_dict)

def thirdTeam(request):
    context_dict = {}

    return render(request, 'website/thirdTeam.html', context=context_dict)

def underTwentyOnes(request):
    context_dict = {}

    return render(request, 'website/underTwentyOnes.html', context=context_dict)

def events(request):

    events_list = Report.objects.filter(news_cat__name = "events")
    context_dict = {"events": events_list}

    return render(request, 'website/events.html', context_dict)

def club_news(request):
    
    news_list = Report.objects.filter(news_cat__name = "club_news")
    context_dict = {"news": news_list,}

    return render(request, 'website/club_news.html', context_dict)

def matchReports(request):
    
    news_list = Report.objects.filter(news_cat__name = "club_news")
    match_reports = Report.objects.filter(news_cat__name = "match_reports")
    context_dict = {"news": news_list, "match_reports": match_reports}

    return render(request, 'website/matchReports.html', context_dict)

def add_report(request):

    form = ReportForm()
    if request.method =="POST":
        form = ReportForm(request.POST)

        if form.is_valid():
            form.save(commit = True)
            return index(request)
        else:
            print(form.errors)
    
    context_dict = {"form": form}

    return render(request, "website/add_news.html", context_dict)


def club_captain(request):
    context_dict = {}

    return render(request, 'website/club_captain.html', context=context_dict)

templates/website/add_news.html
<!DOCTYPE html>

{% extends 'website/base.html' %}
{% load staticfiles %}
{% block title_block %}

{% endblock %}

{% block body_block %}

<h1>Add News</h1>

<div>
    <form id = "report_form" method = "post" action = "/website/add_news/">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            <div class = "datepicker">
                {{ field.help_text }}
                {{ field }}
            </div>
            
        {% endfor %}
        <input type = "submit" name = "submit" value = "Add News" href = "/website/add_news/"/>
    </form>
</div>

<script>
    $(function () {
      $("#id_date").datepicker({
        format:'dd/mm/yyyy',
      });
    });
    $('#id_date').on('click', function(e) {
        e.preventDefault();
        $(this).attr("autocomplete", "off");  
    });
    
</script>

{% endblock %}

templates/website/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-sca;e=1.0">
    <link rel="icon" href="{% static 'images/club_logo.jpg' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>

    <!--Datepicker-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css"
        integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"
        integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

    <title>
        GUFC
    </title>

</head>

{% block title_block %}

{% endblock %}

<body>
    <nav class="navbar navbar-dark navbar-expand-sm sticky-top" style="background-color: black;">
        <a class="navbar-brand" href="/">Home</a>
        <a class="navbar-brand" href="/website/club">The Club</a>
        <li class="nav-item dropdown">
            <a class="navbar-brand" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Teams</a>
            <div class="dropdown-menu" aria-labelledby="dropdown03">
                <a class="dropdown-item" href="/website/firstTeam">1s</a>
                <a class="dropdown-item" href="/website/secondTeam">2s</a>
                <a class="dropdown-item" href="/website/thirdTeam">3s</a>
                <a class="dropdown-item" href="/website/underTwentyOnes">21s</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="navbar-brand" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">News</a>
            <div class="dropdown-menu" aria-labelledby="dropdown03">
                <a class="dropdown-item" href="/website/news">Club News</a>
                <a class="dropdown-item" href="/website/matchReports">Match Reports</a>
                <a class="dropdown-item" href="/website/events">Events</a>
                <a class="dropdown-item" href="/website/add_news/">Add News</a>
            </div>
        </li>
    </nav>

    {% block body_block %}
    {% endblock %}

    <footer class="footer">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" />
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" />
        <div class="container text-center" class="social-network social-circle">
            <a href="https://www.facebook.com/glasgowuniversitymensfootballclub/"><i class="fa fa-facebook"></i></a>
            <a href="https://twitter.com/glasgowunifc"><i class="fa fa-twitter"></i></a>
            <a href="https://www.instagram.com/instagufc/"><i class="fa fa-instagram"></i></a>            
        </div>

    </footer>

</body>

</html>

templates/website/club.html
<!DOCTYPE html>
{% extends 'website/base.html' %}
{% load staticfiles %}
{% block title_block %}

{% endblock %}

{% block body_block %}

<div class="page-header">

    <h1>
        Meet the Committee
        <small>2019/2020</small>
    </h1>

</div>
<br>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
        <div class="col-md-4 col-sm-4">
            <div class="team-member">
                <div class="team-img">
                    <img src="{% static 'images/conor.jpg' %}" alt="team member" class="img-responsive">
                </div>
                <div class="team-hover">
                    <div class="desk">
                        <h4>Club Captain</h4>
                        <p></p>
                    </div>

                </div>
            </div>
            <div class="team-title">
                <h5>Conor Morgan</h5>
                <span>Club Captain</span>
            </div>
        </div>
        <div class="col-md-4 col-sm-4">
            <div class="team-member">
                <div class="team-img">
                    <img src="{% static 'images/gregor.jpg' %}" alt="team member" class="img-responsive">
                </div>
                <div class="team-hover">
                    <div class="desk">
                        <h4>Social Media</h4>
                        <p></p>
                    </div>

                </div>
            </div>
            <div class="team-title">
                <h5>Gregor Kerr</h5>
                <span>Social Media</span>
            </div>
        </div>

    </div>
</div>

<div class="page-header">

    <h1>
        Meet the Coaches
        <small>2019/2020</small>
    </h1>

</div>

<br>

<div class="container">
    <div class="page-header">
        <h1>
            Child Wellbeing and Protection Officer
            <small>2019/2020</small>
        </h1>
    </div>
    <div class="container">
        <div class="row">
            <h3>
                Tom Middlemass - tom.midd@hotmail.com
            </h3>

        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="page-header">
        Club Policies
        <small>2019/2020</small>
        </h1>
    </div>
    <div>
        <ul>
            <li><a href="{% static 'policies/football-men-club-constitution.pdf' %}">Club Constitution</a></li>
            <li><a href="{% static 'policies/equity-policy.pdf' %}">Equity Policy</a></li>
            <li><a href="{% static 'policies/disability-discrimination-policy.pdf' %}">Disability Discrimination
                    Policy</a>
            </li>
            <li><a href="{% static 'policies/unacceptable-conduct-policy.pdf' %}">Unacceptable Conduct
                    Policy</a></li>
            <li><a href="{% static 'policies/code-of-conduct.pdf' %}">Code of Conduct</a></li>
            <li><a href="{% static 'policies/customer-charter.pdf' %}">Customer Charter</a></li>
            <li><a href="{% static 'policies/childwellbeing-protection.pdf' %}">Childwellbeing policy</a></li>
        </ul>
    </div>

    <div class="page-header">
        <h1>
            Find Us
        </h1>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div id="map-container-google-1" class="z-depth-1-half map-container" style="height: 500px">
                    <!--iframe width='100%' height='100%' id='mapcanvas'
                        src='https://maps.google.com/maps?q=Garscube%20Sports%20Complex,%20Glasgow,%20United%20Kingdom&amp;t=&amp;z=10&amp;ie=UTF8&amp;iwloc=&amp;output=embed'
                        frameborder='0' scrolling='no' marginheight='0' marginwidth='0'>

                    </iframe-->

                    <iframe width="600" height="450" frameborder="0" style="border:0" 
                    src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJc9dFaqBFiEgRy4FvIGlpKyQ&key=AIzaSyAzqs96_qPlrDyM0hpZ47BPupSMISbGr8Y" 
                    allowfullscreen></iframe>
                </div>
            </div>
            <div class="col-md-1"></div>

            <div class="col-md-3">
                <h4>West of Scotland Science Park, Maryhill Rd, Glasgow G20 0SP</h4>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>

</div>

{% endblock %}

templates/website/club_captain.html
<!DOCTYPE html>

{% extends 'website/base.html' %}

{% load staticfiles %}
{% block title_block %}

{% endblock %}

{% block body_block %}


{% endblock %}

templates/website/club_news.html
<!DOCTYPE html>

{% extends 'website/base.html' %}
{% load staticfiles %}
{% block title_block %}

{% endblock %}

{% block body_block %}
<div>
    <h1>
    Club News
    </h1>
    {% if news %}
    <ul>
        {% for report in news %}
        <li>
            <h4>{{ report.title}} <small>{{ report.date }}</small></h4>
            <p>{{ report.text }}</p>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <h5>No match reports available</h5>
    {% endif %}
</div>
    
{% endblock %}

templates/website/events.html
<!DOCTYPE html>

{% extends 'website/base.html' %}
{% load staticfiles %}
{% block title_block %}

{% endblock %}

{% block body_block %}
    <h1>Club Events</h1>

    <div>
        {% if events %}
        <ul>
          {% for report in events %}
          <li>
              <h4>{{ report.title }} <small>{{ report.date }}</small></h4>
              <p>{{ report.text }}</p>
          </li>
          {% endfor %}
        </ul>
        {% else %}
        <h5>No club events available</h5>
        {% endif %}
    </div>
    
{% endblock %}

templates/website/firstTeam.html
<!DOCTYPE html>

{% extends 'website/base.html' %}
{% load staticfiles %}
{% block title_block %}

{% endblock %}

{% block body_block %}
<h1>First Team</h1>
<h2>BUCS League</h2>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="thumbnail-container">
                <iframe src='https://bucs.playwaze.com/bucs-football/wxflulchrovm/league-embeddeddisplay/m2k3rlnnxboj'
                    style='' width='100%' height='800' title='BUCS Football' frameborder='0'>
                    <p> Your browser does not support iframes. </p>
                </iframe>
            </div>

        </div>
    </div>

</div>





{% endblock %}

templates/website/index.html
<!DOCTYPE html>
{% extends 'website/base.html' %}
{% load staticfiles %}
{% block title_block %}
{% endblock %}
{% block body_block %}
<!-- Full Page Image Header with Vertically Centered Content -->
<header class="masthead">
    <img src="{% static 'images/Untitled design-4.jpeg' %}" width="100%" height="Full">
    <script>// When the user scrolls the page, execute myFunction
        window.onscroll = function() {myFunction()};
        
        // Get the navbar
        var navbar = document.getElementById("navbar");
        
        // Get the offset position of the navbar
        var sticky = navbar.offsetTop;
        
        // Add the sticky class to the navbar when you reach its scroll position. Remove "sticky" when you leave the scroll position
        function myFunction() {
          if (window.pageYOffset >= sticky) {
            navbar.classList.add("sticky")
          } else {
            navbar.classList.remove("sticky");
          }
        }</script>
</header>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" src="{% static 'images/placeholder.jpg' %}" alt="500x500"            
                data-holder-rendered="true" class="responsive">
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-5">
            <br>
            <br>
            <br>
            <h2 class="featurette-heading"> Our Club History <span class="text-muted">One Club One Family </span>
            </h2>
            <p class="lead">
                Glasgow University Football Club are a Scottish amateur football team based at the Garscube
                Sports Complex in Glasgow,that represents the University of Glasgow. They currently play in the
                Caledonian Amateur Football League.
            </p>

        </div>
    </div>
</div>
<br>
<br>

<div class="container marketing">
    <div class="row">
        <div class="col-lg-2">
            <a href="/website/club"><img class="rounded-circle" src="{% static 'images/club_logo.jpg' %}" width="140"
                    height="140" class="responsive">
                <h2>Our Club</h2>
            </a>
        </div>

        <div class="col-lg-1">
        </div>


        <div class="col-lg-2">
            <a href="/website/matchReports"><img class="rounded-circle" src="{% static 'images/match_report.png' %}"
                    width="140" height="140" class="responsive">
                <h2>News</h2>
            </a>
        </div>

        <div class="col-lg-1">
        </div>


        <div class="col-lg-2">
            <a href="/website/teamProfiles"><img class="rounded-circle" src="{% static 'images/placeholder.jpg' %}"
                    width="140" height="140" class="responsive">
                <h2>Squads </h2>
            </a>
        </div>

        <div class="col-lg-1">
        </div>

        <div class="col-lg-2">
            <a href="/website/events"><img class="rounded-circle" src="{% static 'images/diddies_tournament.jpg' %}"
                    width="140" height="140" class="responsive">
                <h2>Events </h2>
            </a>
        </div>

        <div class="col-lg-1">
        </div>
    </div>

</div>


<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <a class="twitter-timeline" href="https://twitter.com/GlasgowUniFC" data-tweet-limit="2">
                Tweets by @GlasgowUniFC</a>
            <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>

        <div class="col-lg-1">
        </div>


        <div class="col-lg-3">
            <!-- LightWidget WIDGET -->
            <script src="https://cdn.lightwidget.com/widgets/lightwidget.js"></script><iframe
                src="//lightwidget.com/widgets/6bc46a5bc27f5f2ab8bb1c9efc89e27c.html" scrolling="no"
                allowtransparency="true" class="lightwidget-widget"
                style="width:100%;border:0;height:100;overflow:hidden;"></iframe>

        </div>


        <div class="col-lg-3">
            <iframe
                src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fglasgowuniversitymensfootballclub%2F&tabs=timeline&width=340&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId"
                width="340" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0"
                allowTransparency="true" allow="encrypted-media"></iframe>

        </div>
    </div>

</div>
</section>
{% endblock %}

</html>

templates/website/matchReports.html
<!DOCTYPE html>

{% extends 'website/base.html' %}
{% load staticfiles %}
{% block title_block %}

{% endblock %}

{% block body_block %}
          
    <div>
        <h1>
        Match Reports
        </h1>
        {% if match_reports %}
        <ul>
            {% for report in match_reports %}
            <li>
                <h4>{{ report.title}} <small>{{ report.date }}</small></h4>
                <p>{{ report.text }}</p>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <h5>No match reports available</h5>
        {% endif %}
    </div>
      

{% endblock %}

templates/website/secondTeam.html
<!DOCTYPE html>

{% extends 'website/base.html' %}
{% load staticfiles %}
{% block title_block %}

{% endblock %}

{% block body_block %}
<header class="mastheadIndClub">
</header>

<div class="container">
    <div class="row">
        <div class="col-md-4 col-sm-4">
            <div class="team-member">
                <div class="team-img">
                    <img src="{% static 'images/conor.jpg' %}" alt="team member" class="img-responsive">
                </div>
                <div class="team-hover">
                    <div class="desk">
                        <h4>2's Head Coach</h4>
                        <p></p>
                    </div>

                </div>
            </div>
            <div class="team-title">
                <h5>2's Head Coach</h5>
                <span>Coach</span>
            </div>
        </div>
        <div class="col-md-6 col-sm-6">
        </div>
    </div>
</div>

<div class="container">
    <h1>Second Teamss</h1>
    <h2>Saturday League</h2>
    <div class="col-md-12">
        <iframe src='https://www.greaterglasgow.co.uk/item.php?pg=league&pd=1049&it=155' style='' width='100%'
            height='800' title='BUCS Football' frameborder='0'>
            <p> Your browser does not support iframes. </p>
        </iframe>
    </div>
</div>
<br>
<div class="container">
    <h2>BUCS Leagues</h2>
    <div class="container">
        <div class="col-md-12">
            <iframe src='https://bucs.playwaze.com/bucs-football/wxflulchrovm/league-embeddeddisplay/6o2z6kffymik'
                style='' width='100%' height='800' title='BUCS Football' frameborder='0'>
                <p> Your browser does not support iframes. </p>
            </iframe>
        </div>
    </div>
</div>



{% endblock %}

templates/website/teamProfiles.html
<!DOCTYPE html>

{% extends 'website/base.html' %}

{% load staticfiles %}
{% block title_block %}

{% endblock %}

{% block body_block %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card" style="width:400px">
                <img class="card-img-top" src="{% static 'images/placeholder.jpg' %}" alt="Card image">
                <div class="card-body">
                    <h4 class="card-title">First Team</h4>
                    <p class="card-text">2018/2019</p>
                    <a href="/website/firstTeam" class="btn btn-primary">See Profile</a>
                </div>
            </div>
        </div>
        <br>
        <div class="col-md-2">
        </div>
        <div class="col-md-4">
            <div class="card" style="width:400px">
                <img class="card-img-top" src="{% static 'images/placeholder.jpg' %}" alt="Card image">
                <div class="card-body">
                    <h4 class="card-title">Second Team</h4>
                    <p class="card-text">2018/2019</p>
                    <a href="/website/secondTeam" class="btn btn-primary">See Profile</a>
                </div>
            </div>
            <br>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card" style="width:400px">
                <img class="card-img-top" src="{% static 'images/placeholder.jpg' %}" alt="Card image">
                <div class="card-body">
                    <h4 class="card-title">Third Team</h4>
                    <p class="card-text">2018/2019</p>
                    <a href="/website/thirdTeam" class="btn btn-primary">See Profile</a>
                </div>
            </div>
        </div>

        <div class="col-md-2">
        </div>
        <div class="col-md-4">
            <div class="card" style="width:400px">
                <img class="card-img-top" src="{% static 'images/placeholder.jpg' %}" alt="Card image">
                <div class="card-body">
                    <h4 class="card-title">Under 21's</h4>
                    <p class="card-text">2018/2019</p>
                    <a href="/website/underTwentyOnes" class="btn btn-primary">See Profile</a>
                </div>
            </div>
        </div>
        <br>
    </div>
</div>
<br>
<br>
<br>



{% endblock %}

templates/website/thirdTeam.html
<!DOCTYPE html>

{% extends 'website/base.html' %}
{% load staticfiles %}
{% block title_block %}

{% endblock %}

{% block body_block %}
<h1>Third Team</h1>
<h2>Saturday League</h2>
<div class="container">
    <div class="col-md-12">
        <iframe src='https://www.greaterglasgow.co.uk/item.php?pg=league&pd=1049&it=156'style='' width='100%' height='800'
            title='BUCS Football' frameborder='0'>
            <p> Your browser does not support iframes. </p>
        </iframe>

    </div>
</div>
<h2>BUCS League</h2>
<div class="container">
    <div class="col-md-12">
        <iframe src='https://bucs.playwaze.com/bucs-football/wxflulchrovm/league-embeddeddisplay/mblsswq7bfgow' style=''
            width='100%' height='800' title='BUCS Football' frameborder='0'>
            <p> Your browser does not support iframes. </p>
        </iframe>
    </div>
</div>



{% endblock %}

templates/website/underTwentyOnes.html
<!DOCTYPE html>

{% extends 'website/base.html' %}
{% load staticfiles %}
{% block title_block %}

{% endblock %}

{% block body_block %}
<h1>U21 Team</h1>
<h2>Saturday League</h2>
<div class="container">
    <div class="col-md-12">
        <iframe src='http://www.west-of-scotland-21s-football-league.co.uk' style='' width='100%'
            height='800' title='BUCS Football' frameborder='0'>
            <p> Your browser does not support iframes. </p>
        </iframe>
    </div>
</div>
{% endblock %}